# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f5cb0790cf1fc5d99ce447f3e1df54f40217d9abeb91e4c3b776b8735635a78fd8a409f0b8eb4b62eecc6bc98580a3ec38e0c6de3c488ef5cc36a32f9135947

test:
  secret_key_base: 648aff08af1b4db7e35fcfd72f7e08f1cdb28fff84a45f6d94e7e46f6e4147b965fe3af9d9e36482b1a95997ee19b833e5ebd8f7829e9d3085960977e98f5cdd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
